// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Unosquare.ToysAndGames.DBService;

#nullable disable

namespace Unosquare.ToysAndGames.DBService.Migrations
{
    [DbContext(typeof(ToysAndGamesContext))]
    [Migration("20220705014337_createTablesAndData")]
    partial class createTablesAndData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Unosquare.ToysAndGames.DBService.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mattel"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hasbro"
                        });
                });

            modelBuilder.Entity("Unosquare.ToysAndGames.DBService.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AgeRestriction")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRestriction = 12,
                            CompanyId = 1,
                            Description = "lorem ipsum dolor",
                            Name = "Barbie Developer",
                            Price = 300.00m
                        },
                        new
                        {
                            Id = 2,
                            AgeRestriction = 15,
                            CompanyId = 1,
                            Description = "Pista con dos coches etc",
                            Name = "Pista Hotweels",
                            Price = 650.00m
                        },
                        new
                        {
                            Id = 3,
                            AgeRestriction = 99,
                            CompanyId = 2,
                            Description = "Juego de mesa para dos personas",
                            Name = "Adivina quien",
                            Price = 250.00m
                        });
                });

            modelBuilder.Entity("Unosquare.ToysAndGames.DBService.Entities.Product", b =>
                {
                    b.HasOne("Unosquare.ToysAndGames.DBService.Entities.Company", "Company")
                        .WithMany("Products")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Unosquare.ToysAndGames.DBService.Entities.Company", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
