// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Unosquare.ToysAndGames.DBService.Migrations
{
    [DbContext(typeof(ToysAndGamesContext))]
    partial class ToysAndGamesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DBService.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AgeRestriction")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRestriction = 12,
                            Company = "Mattel",
                            Description = "lorem ipsum dolor",
                            Name = "Barbie Developer",
                            Price = 300.00m
                        },
                        new
                        {
                            Id = 2,
                            AgeRestriction = 15,
                            Company = "Mattel",
                            Description = "Pista con dos coches etc",
                            Name = "Pista Hotweels",
                            Price = 650.00m
                        },
                        new
                        {
                            Id = 3,
                            AgeRestriction = 99,
                            Company = "Hasbro",
                            Description = "Juego de mesa para dos personas",
                            Name = "Adivina quien",
                            Price = 250.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
